### ISSUE TITLE
RGS: configuration for stock accounts missing

### ISSUE THREAD

**Issue by astirpe** [onesteinbv/addons-container#39]
Probably also causing this error:

```
2023-08-29 13:51:40,840 14 INFO main odoo.modules.loading: loading stock_account/data/product_data.xml
2023-08-29 13:51:40,847 14 ERROR main odoo.sql_db: bad query: INSERT INTO "ir_property" ("company_id", "create_date", "create_uid", "fields_id", "name", "type", "value_reference", "write_date", "write_uid") VALUES (1, '2023-08-29 13:51:39.529667', 1, 10563, 'property_stock_account_output_categ_id', 'many2one', NULL, '2023-08-29 13:51:39.529667', 1) RETURNING "id"
ERROR: duplicate key value violates unique constraint "ir_property_unique_index"
DETAIL:  Key (fields_id, COALESCE(company_id, 0), COALESCE(res_id, ''::character varying))=(10563, 1, ) already exists.

2023-08-29 13:51:40,851 14 WARNING main odoo.modules.loading: Transient module states were reset
2023-08-29 13:51:40,853 14 ERROR main odoo.modules.registry: Failed to load registry
2023-08-29 13:51:40,854 14 ERROR main click_odoo.env_options: exception
Traceback (most recent call last):
  File "/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/src/odoo/odoo/models.py", line 4358, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/src/odoo/odoo/models.py", line 4280, in _load_records_create
    return self.create(values)
  File "<decorator-gen-71>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_property.py", line 134, in create
    r = super(Property, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 665, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/odoo/models.py", line 3936, in create
    records = self._create(data_list)
  File "/odoo/src/odoo/odoo/models.py", line 4117, in _create
    cr.execute(
  File "/odoo/src/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ir_property_unique_index"
DETAIL:  Key (fields_id, COALESCE(company_id, 0), COALESCE(res_id, ''::character varying))=(10563, 1, ) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/lib/python3.10/site-packages/click_odoo/env_options.py", line 191, in _invoke
    with self.environment_manager(
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/odoo/lib/python3.10/site-packages/click_odoo_contrib/update.py", line 281, in OdooEnvironmentWithUpdate
    _update_db(
  File "/odoo/lib/python3.10/site-packages/click_odoo_contrib/update.py", line 252, in _update_db
    _update_db_nolock(
  File "/odoo/lib/python3.10/site-packages/click_odoo_contrib/update.py", line 230, in _update_db_nolock
    odoo.modules.registry.Registry.new(database, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/src/odoo/odoo/modules/loading.py", line 483, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/src/odoo/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/src/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/src/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/src/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /odoo/src/odoo/addons/stock_account/data/product_data.xml:4, somewhere inside
<record forcecreate="True" id="property_stock_account_output_categ_id" model="ir.property">
            <field name="name">property_stock_account_output_categ_id</field>
            <field name="fields_id" search="[('model','=','product.category'),('name','=','property_stock_account_output_categ_id')]"/>
            <field eval="False" name="value"/>
            <field name="company_id" ref="base.main_company"/>
        </record>
Error: while parsing /odoo/src/odoo/addons/stock_account/data/product_data.xml:4, somewhere inside
<record forcecreate="True" id="property_stock_account_output_categ_id" model="ir.property">
            <field name="name">property_stock_account_output_categ_id</field>
            <field name="fields_id" search="[('model','=','product.category'),('name','=','property_stock_account_output_categ_id')]"/>
            <field eval="False" name="value"/>
            <field name="company_id" ref="base.main_company"/>
        </record>
```

**Comment by ThijsvOers** [comment]
I propose to add the follwing accounts in the standard for the stock accounts (this has to be checked with Joery, I am not sure if the input account is the correct one):
![valuation](https://github.com/onesteinbv/addons-container/assets/30256071/584db1dd-9d67-4825-920c-238a5e3ac41e)

**Comment by astirpe** [comment]
Stock accounts configured in https://github.com/onesteinbv/addons-container/commit/991d16b512859e0d2cfc2aeaf66f35a23b73db99, please let me know whether they will be confirmed or not, after your check with Joery

**Comment by ThijsvOers** [comment]
Checked with Joery, these are the correct settings I also changed the income account and taxes

![image](https://github.com/onesteinbv/addons-container/assets/30256071/0cab35b7-11ff-467f-ab81-4242fad9d811)

**Comment by astirpe** [comment]
Stock account and income account fixed in https://github.com/onesteinbv/addons-container/commit/2abab6b81600586deda32988eed2521a56f0f6c1

Taxes not yet fixed.

**Comment by ThijsvOers** [comment]
@astirpe the account part is tested and ok

**Comment by astirpe** [comment]
For the taxes part, seems more complicated than I expected at first.

The taxes on product category are provided by OCA module `product_category_tax` and there's no mechanism in place to automatically set default values, so that should be implemented.

Second, the product category are not multicompany compliant, so having a solution that automatically sets the taxes from RGS would potentially create problems in a multicompany environment.

There is an OCA module [product_category_inter_company](https://github.com/OCA/multi-company/tree/14.0/product_category_inter_company) that turns the product category to multicompany compliant, but the module must be first ported to V16.

So I will be back on this part as soon as the other priorities will be settle down. Let's keep it open for the time being.

**Comment by ThijsvOers** [comment]
After discussion we decided to not proceed with further enhancements for this last part, the taxes. reasons:
- module is not multi company ready
- - since created service AND goods tax labels we cannot pre configure these taxes
I will closse the task for now

**Comment by astirpe** [comment]
Removed [product_category_tax](https://github.com/onesteinbv/addons-container/commit/d9bd8c6875d612e313da99e88901d1ef80bfc9bc)
