### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#46]
I treid to install the community.install module on the lastest dev instance, got the following error occured during activating the module

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/src/odoo/odoo/models.py", line 4358, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/src/odoo/odoo/models.py", line 4280, in _load_records_create
    return self.create(values)
  File "<decorator-gen-183>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/addons/stock/models/stock_warehouse.py", line 127, in create
    warehouses = super().create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 665, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/src/odoo/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/odoo/src/odoo/odoo/models.py", line 3936, in create
    records = self._create(data_list)
  File "/odoo/src/odoo/odoo/models.py", line 4117, in _create
    cr.execute(
  File "/odoo/src/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "stock_warehouse_warehouse_code_uniq"
DETAIL:  Key (code, company_id)=(WH, 1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/src/odoo/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/src/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoo/src/odoo/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/src/odoo/odoo/http.py", line 1807, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/src/odoo/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/src/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/odoo/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/src/odoo/odoo/modules/loading.py", line 487, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/src/odoo/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/src/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/src/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/src/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/src/odoo/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /odoo/src/odoo/addons/stock/data/stock_data.xml:79, somewhere inside
<record id="warehouse0" model="stock.warehouse">
            <field name="partner_id" ref="base.main_partner"/>
            <field name="code">WH</field>
        </record>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://dev.flavours.k8s.onestein.eu/web/assets/21-04fb39e/web.assets_backend.min.js:970:163)
    at XMLHttpRequest.<anonymous> (https://dev.flavours.k8s.onestein.eu/web/assets/21-04fb39e/web.assets_backend.min.js:978:13)

**Comment by ThijsvOers** [comment]
I do not have the error anymore
