### ISSUE TITLE
jovain error on event ticket

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#53]
In the jovain instance we get an error while opening products, product category. We get the are specific as well on an event while trying to open a product 'ticket'. The error is:

UncaughtPromiseError
Uncaught Promise > Missing field string information for the field 'taxes_updeatable_from_category' from the 'product.template' model
Error: Missing field string information for the field 'taxes_updeatable_from_category' from the 'product.template' model
    at https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6635:258
    at traverse (https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:200)
    at https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:242
    at Function.each (https://jovain.onestein.eu/web/assets/2035-8c0e8d7/web.assets_common.min.js:173:149)
    at traverse (https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:211)
    at https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:242
    at Function.each (https://jovain.onestein.eu/web/assets/2035-8c0e8d7/web.assets_common.min.js:173:149)
    at traverse (https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:211)
    at https://jovain.onestein.eu/web/assets/2036-fa9a700/web.assets_backend.min.js:6630:242
    at Function.each (https://jovain.onestein.eu/web/assets/2035-8c0e8d7/web.assets_common.min.js:173:149)

**Comment by ThijsvOers** [comment]
I believe Andrea removed an oca module (where you can update the taxes on products from the cateory), might this be the issue?
![download](https://github.com/onesteinbv/addons-container/assets/30256071/9c944752-a2cf-4beb-9ab9-bad456fae76a)

**Comment by brambuijs** [comment]
issue has been solved by Anjeel. The module specified by Thijs in the first comment was still listed as installed on the database. yet the module files where not in the addons folder. Solved by uninstalling the module..
