### ISSUE TITLE
Error in VAT report

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#57]
Everytime I click on the loup icon for a line with amount 0,00 I get an error:

UncaughtPromiseError > OwlError
Uncaught Promise > The following error occurred in onWillStart: ""
OwlError: The following error occurred in onWillStart: ""
    at wrapError (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:1592:77)
    at onWillStart (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:1598:117)
    at useModel (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:4768:1)
    at ListController.setup (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:4486:676)
    at new ComponentNode (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:1553:202)
    at https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:2080:6
    at View.slot1 (eval at compile (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:2045:370), <anonymous>:15:36)
    at callSlot (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:1657:25)
    at WithSearch.template (eval at compile (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:2045:370), <anonymous>:8:12)
    at Fiber._render (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/556-8c0e8d7/web.assets_common.min.js:1491:96)

Caused by: UnimplementedRouteError://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5350:91)
    at ORM.fakeRPC [as rpc] (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5416:1377)
    at ORM.call (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:1031:312)
    at Object.preloadSelection [as preload] (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:3626:738)
    at fetchPreloadedData (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5051:326)
    at Record.loadPreloadedData (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5051:613)
    at Record._load (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5083:44)
    at async Record.load (https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5049:1)
    at async https://van-oers-consultancy2.curq.k8s.onestein.eu/web/assets/557-b894cf8/web.assets_backend.min.js:5174:411
    at async Promise.all (index 2)

![image](https://github.com/onesteinbv/addons-container/assets/30256071/62afe47b-f225-4566-b0ac-52d7f6681117)

**Comment by astirpe** [comment]
This is a bug of OCA module account_payment_partner, described in https://github.com/OCA/bank-payment/pull/1125
Fixed in our repo with https://github.com/onesteinbv/addons-oca/commit/e5326455695aaec223e3202d918f966de88de600

**Comment by ThijsvOers** [comment]
tested and ok
